name: Publish to PyPI.org
on:
  release:
    types: [ published ]
jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: build SAIUnit package
        run: |
          python -m pip install --upgrade pip
          python -m build
      - name: Publish SAIUnit package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: build BrainUnit package
        run: |
          python -m pip install dist/saiunit*
          python make_brainunit_setup.py
          cd ./brainunit
          python -m build
      - name: Publish BrainUnit package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
